name: Publish to NPM

on:
   workflow_dispatch:
      inputs:
         version:
            description: 'Version to publish (e.g., patch, minor, major, or specific version)'
            required: true
            default: 'patch'
            type: choice
            options:
               - patch
               - minor
               - major

jobs:
   publish:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - uses: actions/setup-node@v4
           with:
              node-version: '20'
              registry-url: 'https://registry.npmjs.org'

         - uses: pnpm/action-setup@v2
           with:
              version: 8

         - name: Install dependencies
           run: pnpm install

         - name: Run tests
           run: pnpm test

         - name: Build
           run: pnpm build

         - name: Publish to NPM
           run: pnpm publish --access public
           env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

         - name: Update version
           run: |
              git config --global user.name 'GitHub Actions'
              git config --global user.email 'actions@github.com'

              if [[ "${{ github.event.inputs.version }}" =~ ^(patch|minor|major)$ ]]; then
                pnpm version ${{ github.event.inputs.version }}
              else
                pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
              fi

              git add package.json
              git commit -m "chore: bump version after publish"
              git push
              git push --tags
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
